Models/CurrencyInfoModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace VkursiCurrency.Models
{
    public class CurrencyInfoModel
    {
        public int UahAmount { get; set; }
        public string CurrencyType { get; set; }
        public double CurrencyAmount { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace VkursiCurrency.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Controllers/HistoryController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using VkursiCurrency.Services.Interfaces;

namespace VkursiCurrency.Controllers
{
    public class HistoryController : Controller
    {
        private readonly IHistoryService _historyService;

        public HistoryController(IHistoryService historyService)
        {
            _historyService = historyService;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _historyService.GetHistory());
        }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using VkursiCurrency.Models;
using VkursiCurrency.Services.Interfaces;

namespace VkursiCurrency.Controllers
{
    public class HomeController : Controller
    {
        private readonly ICurrencyService _currencyService;
        private readonly IHistoryService _historyService;
        public HomeController(ICurrencyService currencyService, IHistoryService historyService)
        {
            _currencyService = currencyService;
            _historyService = historyService;
        }

        public IActionResult Index()
        {
            return View();
        }

        public async Task<IActionResult> CountCurrency(CurrencyInfoModel model)
        {
            model.CurrencyAmount = await _currencyService.GetCourse(model);
            await _historyService.SaveToHistory(model, User.Identity.Name);
            return View("Index", model);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/History/Index.cshtml
@model IEnumerable<VkursiCurrency.Data.HistoryRecord>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.User)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.UahAmount)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CurrencyType)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CurrencyAmount)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.User)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.UahAmount)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CurrencyType)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CurrencyAmount)
            </td>
        </tr>
}
    </tbody>
</table>

Views/Home/Index.cshtml
@model CurrencyInfoModel
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center" style="border: solid 1px #1b1e21; border-radius: 10px; padding: 20px;">
    <h2>Please choose your currency</h2>
    <form method="post" asp-action="CountCurrency">
        I want to change <input type="number" name="UahAmount"/> UAH for
        <select name="CurrencyType">
            <option>USD</option>
            <option>EUR</option>
        </select>
        <div  style="margin: 10px">
            <button class="btn btn-success" type="submit">Count currency amount</button>
        </div>

        @if(Model != null && Model.CurrencyAmount > 0)
            {
                <p>You can buy @Model.CurrencyAmount @Model.CurrencyType for @Model.UahAmount UAH</p>
            }
        @if(Model != null && Model.CurrencyAmount <= 0)
        { 
            <div style=" width: 400px;margin-left: 31%;width: 400px;border-radius: 10px;background-color: lightcoral;">
                <p>Looks like you inserted wrong amount. Uah amount should be more than 0</p>    
            </div>
        }
    </form>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - VkursiCurrency</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">VkursiCurrency</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="History" asp-action="Index">History</a>
                        </li>
                    </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - VkursiCurrency - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>